version: '2'
services:
  ansible_ssh:
    build: ./ansible
    hostname: ansible_ssh
    restart: always
    volumes:
      - /var/data/ansible_ssh/conf:/etc/ansible
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "2222:22"
